spring:
  application:
    name: apigateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: userservice
          uri: lb://userservice
          predicates:
            - Path=/api/users/**,/api/auth/**,/api/addresses/**,/api/roles/**,/api/permissions/**

        - id: productservice
          uri: lb://productservice
          predicates:
            - Path=/api/products/**,/api/categories/**,/api/variants/**,/api/infos/**

        - id: cartservice
          uri: lb://cartservice
          predicates:
           - Path=/api/carts/**,/api/cartitems/**
           
        - id: orderservice
          uri: lb://orderservice
          predicates:
           - Path=/api/orders/**

        - id: fileservice
          uri: lb://fileservice
          predicates:
           - Path=/api/files/**,/images/**
  main:
    web-application-type: reactive
server:
  port: 8889
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    hostname: localhost
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:localhost:${server.port}
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG